import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { useTranslation } from 'react-i18next';
import { getAccounts, getSavingsGoalById, getTransactions, linkExistingTransferToGoal, recordGoalAllocation, recordOwnedGoalTransfer } from '@/src/db';
import type { AccountWithBalance, SavingsGoalEntryType, SavingsGoalLinkMode, SavingsGoalRow, TransactionWithDetails } from '@/src/db/types';
import { formatMinorUnits, parseMoneyInput } from '@/src/domain/money';
import { planningErrorMessage } from '@/src/domain/planning-error';
import { Colors } from '@/src/constants/theme'; import { useColorScheme } from '@/hooks/use-color-scheme';
import { useDirtyFormGuard } from '@/hooks/use-dirty-form-guard';

const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const nowTime=()=>{const d=new Date();return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;};
export default function GoalEntryForm(){
 const {id}=useLocalSearchParams<{id:string}>(); const router=useRouter(); const {t,i18n}=useTranslation(); const theme=Colors[useColorScheme()??'light']; const locale=i18n.language.startsWith('bn')?'bn':'en';
 const [goal,setGoal]=useState<SavingsGoalRow|null>(null); const [accounts,setAccounts]=useState<AccountWithBalance[]>([]); const [transfers,setTransfers]=useState<TransactionWithDetails[]>([]);
 const [mode,setMode]=useState<SavingsGoalLinkMode>('allocation_only'); const [entryType,setEntryType]=useState<SavingsGoalEntryType>('contribution'); const [amount,setAmount]=useState(''); const [otherAccountId,setOtherAccountId]=useState<string|null>(null); const [transactionId,setTransactionId]=useState<string|null>(null); const [date,setDate]=useState(today()); const [time,setTime]=useState(nowTime()); const [note,setNote]=useState(''); const [saving,setSaving]=useState(false);
 const submitting=useRef(false);
 const initial=useRef(JSON.stringify({mode:'allocation_only',entryType:'contribution',amount:'',otherAccountId:null,transactionId:null,date,time,note:''})); const snapshot=JSON.stringify({mode,entryType,amount,otherAccountId,transactionId,date,time,note}); const allowExit=useDirtyFormGuard(snapshot!==initial.current,t('planning.discardTitle'),t('planning.discardMessage'),t('actions.cancel'),t('planning.discard'));
 useEffect(()=>{Promise.all([getSavingsGoalById(id),getAccounts(),getTransactions({type:'transfer',includeDeleted:false,groupByTransfer:false})]).then(([g,a,tr])=>{setGoal(g);setAccounts(a.filter(x=>x.archived_at===null));setTransfers(tr);}).catch(e=>Alert.alert(t('planning.goalUnavailable'),planningErrorMessage(e,t)));},[id,t]);
 const eligible=useMemo(()=>transfers.filter(tx=>goal&&tx.account_id===goal.linked_account_id&&tx.transfer_role===(entryType==='contribution'?'destination':'source')&&tx.account_currency===goal.currency),[transfers,goal,entryType]);
 const parsed=goal?parseMoneyInput(amount,goal.currency):{valid:false,amountMinor:0};
 const submit=async()=>{if(submitting.current||!goal)return;submitting.current=true;try{if(!parsed.valid)throw new Error('GOAL_ERR_INVALID_AMOUNT');const occurredAt=new Date(`${date}T${time}:00`).getTime();const base={goalId:id,entryType,amountMinor:parsed.amountMinor,occurredAt,occurredOn:date,note};setSaving(true);if(mode==='allocation_only')await recordGoalAllocation(base);else if(mode==='existing_transfer'){if(!transactionId)throw new Error('GOAL_ERR_INVALID_TRANSFER');await linkExistingTransferToGoal({...base,transactionId});}else{if(!otherAccountId)throw new Error('GOAL_ERR_ACCOUNT_NOT_FOUND');await recordOwnedGoalTransfer({...base,otherAccountId});}allowExit();router.back();}catch(e){Alert.alert(t('planning.allocationNotSaved'),planningErrorMessage(e,t));}finally{submitting.current=false;setSaving(false);}};
 const review=()=>{if(!goal||!parsed.valid){Alert.alert(t('planning.allocationNotSaved'),t('planning.errors.generic'));return;}Alert.alert(t('planning.reviewEntry'),`${t(`planning.${entryType}`)}\n${t(`planning.${mode==='allocation_only'?'allocationOnly':mode==='existing_transfer'?'existingTransfer':'ownedTransfer'}`)}\n${formatMinorUnits(parsed.amountMinor,goal.currency,locale)}\n${date} ${time}`,[{text:t('actions.cancel'),style:'cancel'},{text:t('actions.confirm'),onPress:submit}]);};
 const choice=(on:boolean)=>[styles.choice,{backgroundColor:theme.surface,borderColor:on?theme.primary:theme.border}]; const input=[styles.input,{backgroundColor:theme.surface,borderColor:theme.border,color:theme.text}];
 if(!goal)return <SafeAreaView style={[styles.safe,{backgroundColor:theme.background}]}><Text style={{padding:20,color:theme.text}}>{t('status.loading')}</Text></SafeAreaView>;
 return <SafeAreaView style={[styles.safe,{backgroundColor:theme.background}]}><Stack.Screen options={{title:t('planning.addEntry')}}/><KeyboardAvoidingView style={styles.safe} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.body}>
 <Text style={[styles.label,{color:theme.text}]}>{t('planning.entryMode')}</Text>{(['allocation_only','existing_transfer','owned_transfer'] as const).map(m=><TouchableOpacity key={m} accessibilityRole="radio" accessibilityState={{checked:mode===m}} style={choice(mode===m)} onPress={()=>setMode(m)}><Text style={{color:theme.text}}>{t(`planning.${m==='allocation_only'?'allocationOnly':m==='existing_transfer'?'existingTransfer':'ownedTransfer'}`)}</Text></TouchableOpacity>)}
 {(['contribution','withdrawal'] as const).map(v=><TouchableOpacity key={v} accessibilityRole="radio" accessibilityState={{checked:entryType===v}} style={choice(entryType===v)} onPress={()=>{setEntryType(v);setTransactionId(null);}}><Text style={{color:theme.text}}>{t(`planning.${v}`)}</Text></TouchableOpacity>)}
 <Text style={[styles.label,{color:theme.text}]}>{t('planning.amount')}</Text><TextInput accessibilityLabel={t('planning.amount')} style={input} value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/>
 {mode==='existing_transfer'&&<><Text style={[styles.label,{color:theme.text}]}>{t('planning.transferEvidence')}</Text>{eligible.map(tx=><TouchableOpacity key={tx.id} accessibilityRole="radio" accessibilityState={{checked:transactionId===tx.id}} style={choice(transactionId===tx.id)} onPress={()=>{setTransactionId(tx.id);setAmount(formatMinorUnits(tx.amount,goal.currency,'en').replace(/^[^0-9]*/,'').replace(/,/g,''));setDate(tx.occurred_on);}}><Text style={{color:theme.text}}>{tx.occurred_on} · {formatMinorUnits(tx.amount,goal.currency,locale)} · {tx.related_account_name}</Text></TouchableOpacity>)}</>}
 {mode==='owned_transfer'&&<><Text style={[styles.label,{color:theme.text}]}>{t('planning.otherAccount')}</Text>{accounts.filter(a=>a.id!==goal.linked_account_id&&a.currency===goal.currency).map(a=><TouchableOpacity key={a.id} accessibilityRole="radio" accessibilityState={{checked:otherAccountId===a.id}} style={choice(otherAccountId===a.id)} onPress={()=>setOtherAccountId(a.id)}><Text style={{color:theme.text}}>{a.name}</Text></TouchableOpacity>)}</>}
 <Text style={[styles.label,{color:theme.text}]}>{t('planning.date')}</Text><TextInput accessibilityLabel={t('planning.date')} style={input} value={date} onChangeText={setDate}/><Text style={[styles.label,{color:theme.text}]}>{t('planning.time')}</Text><TextInput accessibilityLabel={t('planning.time')} style={input} value={time} onChangeText={setTime}/><Text style={[styles.label,{color:theme.text}]}>{t('planning.noteOptional')}</Text><TextInput accessibilityLabel={t('planning.noteOptional')} multiline style={[input,styles.note]} value={note} onChangeText={setNote}/>
 <TouchableOpacity disabled={saving} accessibilityRole="button" accessibilityState={{disabled:saving}} style={[styles.button,{backgroundColor:theme.primary},saving&&styles.disabled]} onPress={review}><Text style={styles.buttonText}>{saving?t('status.loading'):t('planning.review')}</Text></TouchableOpacity>
 </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1},body:{padding:20,gap:10},label:{fontWeight:'600',marginTop:5},choice:{borderWidth:2,borderRadius:10,minHeight:48,padding:12,justifyContent:'center'},input:{borderWidth:1,borderRadius:10,minHeight:48,padding:12},note:{minHeight:80,textAlignVertical:'top'},button:{minHeight:48,padding:14,borderRadius:10,alignItems:'center',marginTop:10},buttonText:{color:'#fff',fontWeight:'700'},disabled:{opacity:.55}});
